name: StackCraftDemo
canonical: 187-stackcraftdemo
author: Pascal Gasp
description: StackCraftDemo
type: stack
image: ""
keywords:
- StackCraftDemo
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
config:
  pipeline:
    pipeline:
      path: pipeline/terraform-pipeline.yaml
    variables:
      path: pipeline/variables.sample.yaml
